src/Entity/News.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use Gedmo\Mapping\Annotation as Gedmo;


/**
 * @ORM\Entity(repositoryClass="App\Repository\NewsRepository")
 */
class News
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    const SERVER_PATH_TO_IMAGE_FOLDER = '/var/www/ndcsymfony/skeleton/public/img/articles/proba';







    /**
     *@ORM\Column(type="string",name="metatitle",length=70,nullable=true)
     */
    private $metatitle;




    /**
     *@ORM\Column(type="string",name="heading",nullable=true)
     */
    private $heading;


    /**
     * @ORM\Column(type="string",name="metadescription",length=320,nullable=true)
     */
    private $metadescription;




    /**
     * @ORM\Column(type="string",name="metakeywords",nullable=true)
     */
    private $metakeywords;






    /**
     * @ORM\Column(type="text",name="content",nullable=true)
     */
    private $content;




    /**
     * @ORM\Column(type="string",name="fullimagelink",nullable=true)
     */
    private $fullimagelink;


    /**
     * @ORM\Column(type="string",name="innerimage",nullable=true)
     */
    private $innerimage;




    /**
     * @ORM\Column(type="datetime",name="timeadded")
     */
    private $timeadded;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\ArticleCategory",inversedBy="news")
     */
    private $category;

    /**
     * @ORM\Column(type="boolean",name="mainfooter1",options={"default"=true})
     */
    private $mainfooter1;

    /**
     * @ORM\Column(type="boolean",name="mainfooter2",options={"default"=true})
     */
    private $mainfooter2;


    /**
     * @ORM\Column(type="string",length=16,name="navigation",nullable=true)
     */
    private $navigation;


    /**
     * @Gedmo\Timestampable(on="update")
     * @ORM\Column(type="datetime",name="lastmodified",options={"default"=null},nullable=true)
     */
    private $lastmodified;


    /**
     * @ORM\Column(type="boolean",name="live")
     */
    private $live;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Author",inversedBy="news")
     */
    private $author;



    private $coverImageLocation;



    private $file;

    private $file1;

    private $imageLocation;

    private $mainTextWithImage;

    private $image360;





    /**
     * @ORM\Column(type="integer",options={"default"=0},nullable=true)
     */
    private $totalviews;



    /**
     * @Gedmo\Slug(fields={"heading"})
     * @ORM\Column(length=128, unique=true)
     */
    private $slug;


    /**
     * @return mixed
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * @param mixed $id
     */
    public function setId($id): void
    {
        $this->id = $id;
    }


    /**
     * @return mixed
     */
    public function getCategory()
    {
        return $this->category;
    }


    /**
     * @return mixed
     */
    public function getTotalviews()
    {
        return $this->totalviews;
    }



    /**
     * @return mixed
     */
    public function getFile()
    {
        return $this->file;
    }




    /**
     * @return mixed
     */
    public function getFullimagelink()
    {
        return $this->fullimagelink;
    }

    /**
     * @param mixed $fullimagelink
     */
    public function setFullimagelink($fullimagelink): void
    {
        $this->fullimagelink = $fullimagelink;
    }

    /**
     * @return mixed
     */
    public function getMainfooter1()
    {
        return $this->mainfooter1;
    }

    /**
     * @return mixed
     */
    public function getMainfooter2()
    {
        return $this->mainfooter2;
    }







    /**
     * @return mixed
     */
    public function getMetadescription()
    {
        return $this->metadescription;
    }

    /**
     * @return mixed
     */
    public function getMetakeywords()
    {
        return $this->metakeywords;
    }

    /**
     * @return mixed
     */
    public function getTimeadded()
    {
        return $this->timeadded;
    }




    /**
     * @param mixed $file
     */
    public function setFile($file): void
    {
        $this->file = $file;
    }



    /**
     * @param mixed $mainfooter1
     */
    public function setMainfooter1($mainfooter1): void
    {
        $this->mainfooter1 = $mainfooter1;
    }


    /**
     * @param mixed $mainfooter2
     */
    public function setMainfooter2($mainfooter2): void
    {
        $this->mainfooter2 = $mainfooter2;
    }



    /**
     * @param mixed $metakeywords
     */
    public function setMetakeywords($metakeywords): void
    {
        $this->metakeywords = $metakeywords;
    }

    /**
     * @param mixed $totalviews
     */
    public function setTotalviews($totalviews): void
    {
        $this->totalviews = $totalviews;
    }





    /**
     * @param mixed $metadescription
     */
    public function setMetadescription($metadescription): void
    {
        $this->metadescription = $metadescription;
    }

    /**
     * @param mixed $timeadded
     */
    public function setTimeadded($timeadded): void
    {
        $this->timeadded = $timeadded;
    }

    /**
     * @param mixed $category
     */
    public function setCategory($category): void
    {
        $this->category = $category;
    }

    /**
     * @return mixed
     */
    public function getSlug()
    {
        return $this->slug;
    }

    /**
     * @return mixed
     */
    public function getFile1()
    {
        return $this->file1;
    }


    /**
     * @param mixed $file1
     */
    public function setFile1($file1): void
    {
        $this->file1 = $file1;
    }

    /**
     * @return mixed
     */
    public function getInnerimage()
    {
        return $this->innerimage;
    }


    /**
     * @param mixed $innerimage
     */
    public function setInnerimage($innerimage): void
    {
        $this->innerimage = $innerimage;
    }


    /**
     * @return mixed
     */
    public function getImageLocation()
    {
        return $this->imageLocation;
    }

    /**
     * @param mixed $imageLocation
     */
    public function setImageLocation($imageLocation): void
    {
        $this->imageLocation = $imageLocation;
    }

    public function getIntrotext()
    {
        return trim(substr(strip_tags($this->getContent()), 0, 90))."...";
    }


    /**
     * @return mixed
     */
    public function getMainTextWithImage()
    {
        return $this->mainTextWithImage;
    }

    /**
     * @param mixed $mainTextWithImage
     */
    public function setMainTextWithImage($mainTextWithImage): void
    {
        $this->mainTextWithImage = $mainTextWithImage;
    }

    /**
     * @return mixed
     */
    public function getNavigation()
    {
        return $this->navigation;
    }


    /**
     * @param mixed $slug
     */
    public function setSlug($slug): void
    {
        $this->slug = $slug;
    }


    /**
     * @param mixed $navigation
     */
    public function setNavigation($navigation): void
    {
        $this->navigation = $navigation;
    }


    /**
     * @return mixed
     */
    public function getLastmodified()
    {
        return $this->lastmodified;
    }

    /**
     * @param mixed $lastmodified
     */
    public function setLastmodified($lastmodified): void
    {
        $this->lastmodified = $lastmodified;
    }

    public function getGmDate()
    {
        return gmdate("M d,y H:m",strtotime($this->timeadded->format("M d,y H:m")));
    }

    /**
     * @return mixed
     */
    public function getCoverImageLocation()
    {
        return $this->coverImageLocation;
    }

    /**
     * @param mixed $coverImageLocation
     */
    public function setCoverImageLocation($coverImageLocation): void
    {
        $this->coverImageLocation = $coverImageLocation;
    }

    /**
     * @return mixed
     */
    public function getLive()
    {
        return $this->live;
    }


    /**
     * @param mixed $live
     */
    public function setLive($live): void
    {
        $this->live = $live;
    }


    /**
     * @return mixed
     */
    public function getContent()
    {
        return $this->content;
    }

    /**
     * @param mixed $content
     */
    public function setContent($content): void
    {
        $this->content = $content;
    }

    /**
     * @param mixed $heading
     */
    public function setHeading($heading): void
    {
        $this->heading = $heading;
    }

    /**
     * @return mixed
     */
    public function getHeading()
    {
        return $this->heading;
    }

    /**
     * @param mixed $metatitle
     */
    public function setMetatitle($metatitle): void
    {
        $this->metatitle = $metatitle;
    }

    /**
     * @return mixed
     */
    public function getMetatitle()
    {
        return $this->metatitle;
    }

    /**
     * @return mixed
     */
    public function getImage360()
    {
        return $this->image360;
    }

    /**
     * @param mixed $image360
     */
    public function setImage360($image360): void
    {
        $this->image360 = $image360;
    }

    /**
     * @return mixed
     */
    public function getAuthor()
    {
        return $this->author;
    }

    /**
     * @param mixed $author
     */
    public function setAuthor($author): void
    {
        $this->author = $author;
    }










}

templates/base.html.twig
<!doctype html>
<!--[if IE 7]><html class="no-js ie ie7 ie8m" lang="en"><![endif]-->
<!--[if IE 8]><html class="no-js ie ie8 ie8m" lang="en"><![endif]-->
<!--[if IE 9]><html class="no-js ie ie9" lang="en" ><![endif]-->
<!--[if !IE]><!--><html class="no-js" lang="en"><!--<![endif]-->

    {% block head %}
        <head>
            <!-- Google Tag Manager -->
            <script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
                        new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
                    j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
                    'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
                })(window,document,'script','dataLayer','GTM-PS2HV78');</script>
            <!-- End Google Tag Manager -->
            <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
            <title>{% block title %}{{ page.metatitle|default('No Deposit Casino')|shortCodes }}{% endblock %}</title>
            <meta name="description" content="{% block metaDescription %}{{ page.metadescription|default('No Deposit Casino')|shortCodes }}{% endblock %} "/>
            <meta property="og:title" content="{% block ogtitle %}{{ page.metatitle|default('No Deposit Casino')|shortCodes }}{% endblock %}" />
            {%if page is defined %}<meta property="og:description" content="{% block ogdescription %}{{ page.metadescription|shortCodes }}{% endblock %}" />{% endif %}
            <meta name="keywords" content="{% block metakeywords %}{{ page.metakeywords|default('No Deposit Casino')|shortCodes }}{% endblock %}"/>
            <meta property="og:url" content=" {{ app.request.uri  }}" />
            <meta property="og:type" content="website" />
            <meta property="og:image" content="https://nodepositcasino.org/public/img/ndc-logo.png" />
            <meta name="viewport" content="width=device-width,initial-scale=1">
            <meta name="robots" content="{% block meta_follow %}all{% endblock %}" />
            <meta name="google-signin-client_id" content="{{ new_google_client_id }}">
            <link rel="canonical" href="{{ app.request.uri }}" />
            <link rel="icon" href="{{ asset('ndc_favicon.ico') }}" type="image/x-icon"/>
            <link rel="shortcut icon" href="{{ asset('ndc_favicon.ico') }}" type="image/x-icon"/>
            <link href="https://fonts.googleapis.com/css?family=Raleway:300,400,500|Roboto:400,500,700" rel="stylesheet">
            <!--[if lt IE 7]><link rel="stylesheet" href="{{ asset('css/ie-old.css') }}"><![endif]-->
            <link rel="stylesheet" href="{{ asset('build/app.css') }}">
        </head>
    {% endblock %}

    <body class="{{ bodyclass|default('template-page') }}" >

    <!-- Google Tag Manager (noscript) -->
        <noscript>
            <iframe src="https://www.googletagmanager.com/ns.html?id=GTM-PS2HV78" height="0" width="0" style="display:none;visibility:hidden"></iframe>
        </noscript>
        <!-- End Google Tag Manager (noscript) -->
            <div id="fb-root"></div>
            <script>(function(d, s, id) {
                    var js, fjs = d.getElementsByTagName(s)[0];
                    if (d.getElementById(id)) return;
                    js = d.createElement(s); js.id = id;
                    js.src = 'https://connect.facebook.net/en_US/sdk.js#xfbml=1&version=v3.0&appId=1945076775524520&autoLogAppEvents=1';
                    fjs.parentNode.insertBefore(js, fjs);
                }(document, 'script', 'facebook-jssdk'));
            </script>

            <div id="jqtoast-tr" class="freeow freeow-top-right"></div>
            <div id="jqtoast-br" class="freeow freeow-bottom-right"></div>
            <!--[if lt IE 7]><p class="chromeframe">Your browser is <em>ancient!</em> <a href="//browsehappy.com/">Upgrade to a different browser</a> or <a href="//www.google.com/chromeframe/?redirect=true">install Google Chrome Frame</a> to experience this site.</p><![endif]-->

            <div id="welcomeDiv" class="alertBox">
                <div class="welcomeDivBox">
                    <span class="alertLike"></span>
                    <span id='alert'></span>
                </div>
            </div>

            <div id="unlikeAlert" class="alertBox">
                <span class="alertUnlike"></span>
                <span id='alert2'></span>
            </div>


            <div class="header-holder {% if page.fullimagelink is defined and page.fullimagelink != null %}cover-image-header{% endif %}">
                {{ render(controller(
                    'App\\Controller\\TemplateController::header'
                    ))
                }}
                {% block bodyheader %}{% endblock %}
            </div><!--/.header-holder-->

            <div class="main-container"><!-- START MAIN CONTENT-->
                {% block main %}{% endblock %}
            </div><!-- END MAIN CONTENT-->


            {% block footer %}
                {%if page is defined %}
                    {{ render(controller(
                        'App\\Controller\\TemplateController::footer',
                            { 'page':page }
                        ))
                    }}
                {% endif %}
            {% endblock %}

            {% block commonjs %}
                <script src="{{ asset('js/ouibounce/ouibounce.min.js') }}"></script>
                <script src="https://apis.google.com/js/platform.js" async defer></script>
                <script src="{{ asset('build/app.js') }}"></script>
                <script src="{{ asset('js/google_sign_in.js') }}" async defer></script>

                <!--[if (gte IE 6)&(lte IE 8)]><script src="{{ asset('js/selectivizr.js') }}"></script><![endif]-->
                <script>
                    (function (d, t) {
                        var bh = d.createElement(t), s = d.getElementsByTagName(t)[0];
                        bh.type="text/javascript";
                        bh.src="//www.bugherd.com/sidebarv2.js?apikey=dsqpjvcppyf4uqahqbcdja";
                        s.parentNode.insertBefore(bh, s);
                    })(document, "script");
                </script>

                <script type="application/ld+json">
                {
                  "@context": "http://schema.org/",
                  "@type": "Organization",
                  "name": "No Deposit Casino",
                  "url": "https://nodepositcasino.org/",
                  "logo": "https://nodepositcasino.org/img/logo.png"
                }
                </script>
            {% endblock %}

            {% block mainSchemaParameters %}
                <script type="application/ld+json">
                {
                    "@context": "http://schema.org",
                    "@type": "WebPage",
                    "name": "{{ page.metatitle|default('No Deposit Casino')|shortCodes }}",
                    "description": "{{ page.metadescription|default('No Deposit Casino')|shortCodes }}",
                    "publisher": {
                        "@type": "Organization",
                        "name": "No Deposit Casino"
                    }
                }
                </script>
            {% endblock %}

            {% if(page.navigation is defined and page.navigation|length > 0) %}
                <script>
                    $(document).ready(function() {
                        $("[data-page={{ page.navigation }}]").addClass("active");
                    });
                </script>
            {% endif %}

            {% block javascripts %}
            {% endblock %}

        </body>
</html>

templates/casino_softwares_for_country_list.html.twig
{% set i=0 %}
{% for software in softwares %}
    {% set i=i+1 %}
    {% set softwaresLength = softwares|length %}
    {% if i < 4 or softwaresLength == 4 %}
        <img src="data:image/gif;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAIAAACQd1PeAAAADElEQVQIHWO4/+INAAVdArRD1D4LAAAAAElFTkSuQmCC"
     data-original='{{ software.image25 }}' style='opacity:{% if(software.restrictedcountries.contains(country)) %}0.3{% else %}1{% endif %}' alt='Powered By {{ software.title }}' title='Powered By {{ software.title }}' width="25" height="15" class="lazyload">
    {% endif %}

    {%  if i==4 and softwaresLength >4   %}
        {% set softwaresNum=softwaresLength - 3 %}
        {% if casinosPage is defined %}
            <div class='more-softwares'>+{{ softwaresNum }}
            <div class='softwares_hover'>
            {% else %}
            <div class='more-softwares'>+{{ softwaresNum }}
                <div class='softwares_hover softwares_hoverSlide'>
            {% endif %}
    {% endif %}


    {% if i>=4 and softwaresLength > 4 %}
        <img src="data:image/gif;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAIAAACQd1PeAAAADElEQVQIHWO4/+INAAVdArRD1D4LAAAAAElFTkSuQmCC"
     data-original='{{ software.image25 }}' style='opacity:{% if(software.restrictedcountries.contains(country)) %}0.3{% else %}1{% endif %}' alt='Powered By {{ software.title }}' title='Powered By {{ software.title }}' width="25" height="15" class="lazyload">
    {% endif %}

    {% if softwaresLength >4 and i==softwaresLength %}
                </div>
            </div>
    {% endif %}
{% endfor %}

templates/contact_us.html.twig
{% extends 'base.html.twig' %}

    {% block bodyheader %}
        <div class="header-content">
            <div class="container">
                <div class="ad-line">
                </div><!--/.ad-line-->
                <h1 class="page-title">{{ page.heading }}</h1>
            </div><!--/.wrap-->
        </div><!--/#content-header-->
    {% endblock %}


    {% block main %}
        <div class="text-holder container-narrow">
            <a class="scroll-to-button scroll-to-link" href="#button-link-1" aria-label="Scroll to contact">
                <i class="fas fa-arrow-down" aria-hidden="true"></i>
            </a>
            <div id="contactresponse"></div>
            <div class="contact-form padding-large">
                <span id="button-link-1"></span>
                <div class="form-row">
                     <div class="col-md-6">
                         <div class="form-group">
                             <input type="text" id="contactname" aria-label="Name *" placeholder="Name *" required class="contact-form-field">
                         </div>
                     </div>
                     <div class="col-md-6">
                         <div class="form-group">
                             <input type="text" id="contactemail" aria-label="Email *" placeholder="Email *" required class="contact-form-field">
                         </div>
                     </div>
                </div>
                <div class="form-group">
                        <textarea id="contactcontent" name="content" aria-label="Your Comment or Question *" placeholder="Your Comment or Question *" required class="contact-form-field"></textarea>
                </div>
                <p id="contact-error" class="invalid-feedback"> * These Fields Are Mandatory.</p>
                <button id="contact" class="btn btn-primary">Submit</button>
            </div>
        </div>
            <!-- END MAIN CONTENT-->

    {% endblock %}

templates/latest_news_articles_index.html.twig
<div class="latest-news-section">
    <a class="scroll-to-button scroll-to-link" href="#button-link-4" aria-label="Scroll to Latest news">
        <i class="fas fa-arrow-down" aria-hidden="true"></i>
    </a>
    <div class="articles-holder container" id="button-link-4">
        <div class="latest-news-header">
            <h2>Latest News</h2>
            <a class="btn btn-primary" href="{{ path('news') }}">View all news</a>
        </div>
        <div class="row">
            {% set counter=0 %}
            {% for singlenews in news  %}
                {% set counter=counter+1 %}
                <div itemscope itemtype="http://schema.org/NewsArticle" class="article-box col-lg-4 col-sm-6 col-12 {% if counter==3 %} {{ 'd-none d-lg-block' }} {% endif %} ">
                    <meta  itemprop="image" content="{{ absolute_url(singlenews.image360) }}" />
                    <meta  itemprop="mainEntityOfPage" content="{{ absolute_url(path('singlenews',{slug:singlenews.slug})) }}" />
                    <meta  itemprop="url" content="{{ absolute_url(path('singlenews',{slug:singlenews.slug})) }}" />
                    <meta itemprop="datePublished" content="{{ singlenews.timeadded|date('Y-m-d') }}" />
                    <meta itemprop="dateModified" content="{{ singlenews.lastmodified|date('Y-m-d') }}" />
                    <div class="article-box-inner">
                        <div class="article-box-image">
                            <a href="{{ path('singlenews',{slug:singlenews.slug}) }}">
                                <img class="lazyload" src="{{asset(('img/lazy-360.png'))}}" data-original="{{ singlenews.image360 }}" alt="{{ singlenews.heading }} " width="360" height="220">
                            </a>
                        </div>
                        <div class="article-box-content">
                            <h3>
                                <a href="{{ path('singlenews',{slug:singlenews.slug}) }}"><span itemprop="headline">{{ singlenews.heading }}</span></a>
                            </h3>
                            <p class="article-box-date">{{ singlenews.gmdate }}</p>
                            {% if singlenews.author %}
                                <p class="article-box-author">author: <a href="{{ path('author',{"slug":singlenews.author.slug}) }}"><span itemprop="author">{{ singlenews.author.authorname }}</span></a></p>
                            {% endif %}
                            <p class="article-box-descr">{{ singlenews.introtext|raw }}</p>
                            <a class="read-more" href="/news/{{ singlenews.slug }}">Read more</a>
                        </div>
                    </div>
                    <div class="d-none" itemprop="publisher" itemscope itemtype="https://schema.org/Organization" >
                        <div class="d-none" itemprop="logo" itemscope itemtype="https://schema.org/ImageObject">
                            <img src="https://nodepositcasino.org/img/logo.svg"/>
                            <meta itemprop="url" content="https://nodepositcasino.org/img/logo.png">
                            <meta itemprop="width" content="400">
                            <meta itemprop="height" content="60">
                        </div>
                        <meta itemprop="name" content="No Deposit Casino">
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>

    <div class="articles-holder container" id="button-link-4">
        <div class="latest-news-header">
            <h2>Latest Articles</h2>
            <a class="btn btn-primary" href="{{ path('articles') }}">View all Articles</a>
        </div>
        <div class="row">
            {% set counter=0 %}
            {% for article in articles  %}
                {% set counter=counter+1 %}
                <div itemscope itemtype="http://schema.org/NewsArticle" class="article-box col-lg-4 col-sm-6 col-12 {% if counter==3 %} {{ 'd-none d-lg-block' }} {% endif %} ">
                    <meta  itemprop="image" content="{{ absolute_url(article.image360) }}" />
                    <meta  itemprop="mainEntityOfPage" content="{{ absolute_url(path('article',{slug:article.slug})) }}" />
                    <meta  itemprop="url" content="{{ absolute_url(path('article',{slug:article.slug})) }}" />
                    <meta itemprop="datePublished" content="{{ article.timeadded|date('Y-m-d') }}" />
                    <meta itemprop="dateModified" content="{{ article.lastmodified|date('Y-m-d') }}" />
                    <div class="article-box-inner">
                        <div class="article-box-image">
                            <a href="{{ path('article',{slug:article.slug}) }}">
                                <img class="lazyload" src="{{asset(('img/lazy-360.png'))}}" data-original="{{ article.image360 }}" alt="{{ article.heading }} " width="360" height="220">
                            </a>
                        </div>
                        <div class="article-box-content">
                            <h3>
                                <a href="{{ path('article',{slug:article.slug}) }}"><span itemprop="headline">{{ article.heading }}</span></a>
                            </h3>
                            <p class="article-box-date">{{ article.gmdate }}</p>

                            <p class="article-box-descr">{{ article.introtext|raw }}</p>
                            <a class="read-more" href="{{ path('article',{slug:article.slug}) }}">Read more</a>
                        </div>
                    </div>
                    <div class="d-none" itemprop="publisher" itemscope itemtype="https://schema.org/Organization" >
                        <div class="d-none" itemprop="logo" itemscope itemtype="https://schema.org/ImageObject">
                            <img src="https://nodepositcasino.org/img/logo.svg"/>
                            <meta itemprop="url" content="https://nodepositcasino.org/img/logo.png">
                            <meta itemprop="width" content="400">
                            <meta itemprop="height" content="60">
                        </div>
                        <meta itemprop="name" content="No Deposit Casino">
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
</div>

templates/privacy.html.twig
{% extends 'base.html.twig' %}


    {% block bodyheader %}
        <div class="header-content">
            <div class="container">
                <div class="ad-line">
                </div><!--/.ad-line-->
                <h1 class="page-title">{{ page.heading }}</h1>
            </div><!--/.wrap-->
        </div><!--/#content-header-->
    {% endblock %}


    {% block main %}
        <div class="text-holder container">
            <a class="scroll-to-button scroll-to-link" href="#button-link-1" aria-label="Scroll to Privacy policy">
                <i class="fas fa-arrow-down" aria-hidden="true"></i>
            </a>
            <span id="button-link-1"></span>
            {{ page.content|raw }}
        </div>
        <!-- END MAIN CONTENT-->
    {% endblock %}

templates/register_confirmation.html.twig
{% extends 'base.html.twig' %}

    {% block main %}
        <div class="container">
            <p style="text-align: center; margin-top: 2em; font-size: 1.4em;">
                Thanks for registering! Your account is now active.
            </p>
        </div>
    {% endblock %}

templates/reset_password_form.html.twig
<form id="reset_password_form">
    <div class="form-group">
        <input id="reset_email" type="email" aria-label="Type in your e-mail" placeholder="Type in your e-mail" required>
    </div>
    <div class="form-group">
        <button class="btn btn-primary btn-small btn-shadow">Reset Password</button>
    </div>
    <p id="reset_password_info"></p>
</form>

templates/search.html.twig
{% extends 'base.html.twig' %}

    {% block bodyheader %}
        <div class="header-content">

            <div class="container">

                <div class="ad-line"></div><!--/.ad-line-->
                <h1 class="page-title">{{ page.heading }}</h1>
            </div><!--/.wrap-->
        </div><!--/#content-header-->
    {% endblock %}


    {% block main %}
        <!-- START MAIN CONTENT-->
        {% if error is defined %}
            <div class="text-holder container">
                <h4>{{ error }}</h4>
            </div><!--/#content-->
        {% else %}
            <div class="text-holder">
                <a class="scroll-to-button scroll-to-link" href="#button-link-1" aria-label="Scroll to Search results">
                    <i class="fas fa-arrow-down" aria-hidden="true"></i>
                </a>

                <div class="list-data container">
                    <h1>Search results</h1>
                    <span id="button-link-1"></span>
                    <div class="casinos-list">
                        {{ casinos|raw }}
                    </div>
                </div>
            </div><!--/#container-->
            {% endif %}
    {% endblock %}

templates/section_interest.html.twig
<div class="section-interest">
    <a class="scroll-to-button scroll-to-link" href="#button-link-5" aria-label="Scroll to Interested articles">
        <i class="fas fa-arrow-down" aria-hidden="true"></i>
    </a>
    <div class="container">
        <h2 class="text-center"><span id="button-link-5"></span>You May Be Interested In</h3>
        <div class="articles-holder">
            <div class="row justify-content-center">
                {% for article in articles  %}
                    <div class="article-box col-lg-4 col-md-6">
                        <div class="article-box-inner">
                            <div class="article-box-image">
                                <a href="{{ path('article', { slug: article.slug }) }}">
                                    <img class="lazyload" src="{{asset(('img/lazy-360.png'))}}" data-original="{{ article.image360 }}" alt="{{ article.heading }}" width="360" height="200"/>
                                </a>
                            </div>
                            <div class="article-box-content">
                                <h3>
                                    <a href="{{ path('article', { slug: article.slug }) }}">{{ article.heading }}</a>
                                </h3>
                                <p class="article-box-date">{{ article.gmdate }}</p>
                                <p class="article-box-descr">{{ article.introtext|raw }}</p>
                                <div class="d-flex justify-content-between">
                                    <a class="read-more" href="{{ path('article', { slug: article.slug }) }}">Read more</a>
                                    <span class="views-no"><span class="icon"></span>{{ article.totalviews }}</span>
                                </div>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>
</div>